services:

  db:
    image: postgres:16

    environment:
      POSTGRES_PASSWORD: 34865
      POSTGRES_DB: complaint_system

    volumes:
      - db-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:34865@db:5432/complaint_system
      AWS_PROFILE: complaint_system
      AWS_REGION: us-east-1
      AWS_BUCKET_NAME: vm-complaint-system-bucket

    ports:
      - "5001:5000"

    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data: