"""add sentiment to complaints

Revision ID: 21a04a2fea27
Revises: 2482e4a3ccd2
Create Date: 2026-08-31 17:26:35.563380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21a04a2fea27'
down_revision = '2482e4a3ccd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_complaints', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
