"""add contained pii

Revision ID: 7fadde7a764d
Revises: 21a04a2fea27
Create Date: 2026-09-01 17:11:21.541822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fadde7a764d'
down_revision = '21a04a2fea27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_complaints', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('contained_pii', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("contained_pii", sa.Boolean(), nullable=False, server_default=sa.text("false")))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_complaints', schema=None) as batch_op:
        batch_op.drop_column('contained_pii')

    # ### end Alembic commands ###
