"""add document text to complaints

Revision ID: 82033ab06e7b
Revises: 7fadde7a764d
Create Date: 2026-09-03 12:42:54.889451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82033ab06e7b'
down_revision = '7fadde7a764d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_complaints', schema=None) as batch_op:
        batch_op.drop_column('document_text')

    # ### end Alembic commands ###
