"""add priority override reason

Revision ID: c20e29e0c27f
Revises: 82033ab06e7b
Create Date: 2026-09-03 16:06:17.461635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20e29e0c27f'
down_revision = '82033ab06e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('priority_override_reason', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_complaints', schema=None) as batch_op:
        batch_op.drop_column('priority_override_reason')

    # ### end Alembic commands ###
